---
"$schema": http://json-schema.org/draft-04/schema#
title: Bioboxes Profiling
type: object
properties:
  version:
    type: string
    pattern: "^1.0.\\d+$"
  arguments:
    type: array
    required:
    - fastq
    - database
    additionalItems: false
    minItems: 1
    items:
      oneOf:
      - "$ref": "#/definitions/fastq"
      - "$ref": "#/definitions/database"
      - "$ref": "#/definitions/cache"
required:
- version
- arguments
additionalProperties: false
definitions:
  fastq:
    type: object
    minItems: 1
    required:
    - fastq
    properties:
      fastq:
        "$ref": "#/definitions/values"
  values:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: object
      additionalProperties: false
      required:
      - type
      - value
      properties:
        type: {}
        value: {}
  cache:
    type: object
    required:
    - cache
    properties:
      cache:
        required:
        - type
        - value
        properties:
          type: {}
          value: {}
  database:
    required:
    - database
    properties:
      database:
        required:
        - type
        - value
        properties:
          type: {}
          value: {}
